// Toutes les communes d'Algérie — 1541 communes réparties sur 48 wilayas
// Coordonnées approximatives pour les chefs-lieux de daïra
export const COMMUNES_ALL: Record<string, { nom: string; lat?: number; lng?: number }[]> = {
  "01": [ // Adrar
    { nom: "Adrar", lat: 27.8742, lng: -0.2939 },
    { nom: "Aoulef", lat: 26.9728, lng: 1.0797 },
    { nom: "Reggane", lat: 26.7106, lng: 0.1669 },
    { nom: "Timimoun", lat: 29.2597, lng: 0.2303 },
    { nom: "In Zghmir" },
    { nom: "Aougrout", lat: 28.1264, lng: -0.0733 },
    { nom: "Zaouiet Kounta", lat: 27.2351, lng: -0.1858 },
    { nom: "Sali" },
    { nom: "Tamentit", lat: 27.6694, lng: -0.2344 },
    { nom: "Akabli", lat: 26.7072, lng: 1.3578 },
    { nom: "Tsabit", lat: 28.3561, lng: -0.2717 },
    { nom: "Fenoughil", lat: 27.9711, lng: -0.6322 },
    { nom: "Aougrout" },
    { nom: "Deldoul" },
    { nom: "Charouine", lat: 29.0233, lng: -0.2694 },
    { nom: "Bordj Badji Mokhtar", lat: 21.3281, lng: 0.9536 },
    { nom: "Timiaouine" },
    { nom: "In Guezzam" },
    { nom: "Bouda" },
    { nom: "Metarfa" },
    { nom: "Ouled Ahmed Timmi" },
    { nom: "Talmine" },
    { nom: "Tinerkouk" },
  ],
  "02": [ // Chlef
    { nom: "Chlef", lat: 36.1647, lng: 1.3317 },
    { nom: "Ténès", lat: 36.5153, lng: 1.3136 },
    { nom: "El Karimia", lat: 36.0672, lng: 1.5522 },
    { nom: "Abou El Hassan", lat: 36.3542, lng: 1.5317 },
    { nom: "Oum Drou", lat: 36.2167, lng: 1.5 },
    { nom: "Sendjas", lat: 36.2042, lng: 1.5667 },
    { nom: "Boukadir", lat: 36.0742, lng: 1.1006 },
    { nom: "Ouled Fares", lat: 36.1817, lng: 1.1919 },
    { nom: "Bénairia" },
    { nom: "Aïn Merane", lat: 36.2264, lng: 1.8519 },
    { nom: "Chettia", lat: 36.1983, lng: 1.4278 },
    { nom: "Sobha" },
    { nom: "El Hadjadj" },
    { nom: "Taougrite" },
    { nom: "Bréa" },
    { nom: "El Marsa" },
    { nom: "Ouled Abbes" },
    { nom: "Sidi Abderrahmane" },
    { nom: "Herenfa" },
    { nom: "Oued Goussine" },
    { nom: "Zeboudja" },
    { nom: "Aïn Bouchekif" },
    { nom: "Larabaa" },
    { nom: "Talassa" },
    { nom: "Oued Fodda", lat: 36.1906, lng: 1.5367 },
  ],
  "03": [ // Laghouat
    { nom: "Laghouat", lat: 33.8, lng: 2.8667 },
    { nom: "Aflou", lat: 34.1114, lng: 2.0997 },
    { nom: "Hassi Rmel", lat: 32.9297, lng: 3.2811 },
    { nom: "Sidi Makhlouf", lat: 33.7567, lng: 2.9117 },
    { nom: "Gueltat Sidi Saâd", lat: 33.4628, lng: 2.5264 },
    { nom: "Ksar El Hirane", lat: 33.7819, lng: 3.3217 },
    { nom: "El Assafia" },
    { nom: "El Ghicha" },
    { nom: "Beidha" },
    { nom: "Brida" },
    { nom: "Aïn Madhi", lat: 33.8022, lng: 2.6694 },
    { nom: "Ben Nacer Ben Chohra" },
    { nom: "Sidi Bouzid" },
    { nom: "Sebgag" },
    { nom: "El Houaita" },
    { nom: "Aïn Sidi Ali" },
    { nom: "Tadjmout", lat: 33.8756, lng: 2.5428 },
    { nom: "Hassi Delaa" },
    { nom: "Oued Morra" },
    { nom: "Hadj Mechri" },
    { nom: "El Haouaita" },
    { nom: "Aïn Mahdi" },
    { nom: "Sidi Makhlouf" },
    { nom: "Oued Serrat" },
  ],
  "04": [ // Oum El Bouaghi
    { nom: "Oum El Bouaghi", lat: 35.8758, lng: 7.1133 },
    { nom: "Aïn Beïda", lat: 35.7983, lng: 7.3928 },
    { nom: "Aïn Fakroun", lat: 35.9817, lng: 7.4753 },
    { nom: "Aïn Mlila", lat: 35.8681, lng: 7.2789 },
    { nom: "Souk Naamane", lat: 35.9742, lng: 7.3422 },
    { nom: "El Amiria", lat: 35.8181, lng: 7.2308 },
    { nom: "Aïn Kercha", lat: 35.7211, lng: 7.1969 },
    { nom: "Hanchir Toumghani" },
    { nom: "El Belala" },
    { nom: "Dhalaa" },
    { nom: "Berriche" },
    { nom: "El Djazia" },
    { nom: "Fkirina" },
    { nom: "Rahia" },
    { nom: "Oued Nini" },
    { nom: "Meskiana", lat: 35.6378, lng: 7.6636 },
    { nom: "Sigus" },
    { nom: "Aïn Zitoun" },
    { nom: "El Fedjoudj" },
    { nom: "Ouled Gacem" },
    { nom: "Zorg" },
    { nom: "Aïn Babouche" },
    { nom: "Ksar Sbahi" },
    { nom: "Ouled Hamla" },
    { nom: "Foum Toub" },
  ],
  "05": [ // Batna
    { nom: "Batna", lat: 35.5553, lng: 6.1742 },
    { nom: "Aïn Touta", lat: 35.3703, lng: 5.8939 },
    { nom: "Arris", lat: 35.2161, lng: 6.3228 },
    { nom: "Barika", lat: 35.3881, lng: 5.3669 },
    { nom: "Merouana", lat: 35.6361, lng: 5.9211 },
    { nom: "Tazoult", lat: 35.4783, lng: 6.2728 },
    { nom: "Ngaous", lat: 35.5614, lng: 5.6122 },
    { nom: "Tkout", lat: 35.0303, lng: 6.4556 },
    { nom: "Timgad", lat: 35.4864, lng: 6.4708 },
    { nom: "Oued El Ma" },
    { nom: "Aïn Djasser" },
    { nom: "Ouled Si Slimane" },
    { nom: "Ghassira" },
    { nom: "Inoughissen" },
    { nom: "Taxlent" },
    { nom: "El Madher" },
    { nom: "Seriana" },
    { nom: "Boumia" },
    { nom: "Djerma" },
    { nom: "Boulhilet" },
    { nom: "Lazrou" },
    { nom: "Tigherghar" },
    { nom: "Menaa", lat: 35.1278, lng: 6.2556 },
    { nom: "Ouled Aouf" },
    { nom: "Boulhilat" },
    { nom: "Oued Chaaba" },
    { nom: "Seggana" },
    { nom: "Ichmoul" },
    { nom: "Chir" },
    { nom: "Bitam" },
    { nom: "El Hassi" },
    { nom: "Foum Toub" },
    { nom: "Ain Yagout" },
    { nom: "Amdoukal" },
    { nom: "El Djezar" },
    { nom: "Lemsane" },
    { nom: "Oued Taga" },
  ],
  "06": [ // Béjaïa
    { nom: "Béjaïa", lat: 36.7539, lng: 5.0569 },
    { nom: "Akbou", lat: 36.4639, lng: 4.5286 },
    { nom: "El Kseur", lat: 36.6681, lng: 4.8578 },
    { nom: "Aokas", lat: 36.7797, lng: 5.2453 },
    { nom: "Souk El Tenine", lat: 36.8333, lng: 5.4 },
    { nom: "Tichy", lat: 36.7225, lng: 5.1267 },
    { nom: "Amizour", lat: 36.6483, lng: 5.1 },
    { nom: "Kherrata", lat: 36.5017, lng: 5.2806 },
    { nom: "Chemini" },
    { nom: "Sidi Aïch", lat: 36.6203, lng: 4.7053 },
    { nom: "Barbacha" },
    { nom: "Bejaia" },
    { nom: "Ighil Ali" },
    { nom: "Amalou" },
    { nom: "Tazmalt", lat: 36.3989, lng: 4.3986 },
    { nom: "Adekar" },
    { nom: "Aïn Legraj" },
    { nom: "Timezrit" },
    { nom: "Kendira" },
    { nom: "Oued Ghir" },
    { nom: "Beni Ksila" },
    { nom: "Fenaia Ilmaten" },
    { nom: "Bouhamza" },
    { nom: "Chelata" },
    { nom: "Darguina" },
    { nom: "Draâ El Caïd" },
    { nom: "Ait Smail" },
    { nom: "Tibane" },
    { nom: "Beni Maouche" },
    { nom: "Boudjellil" },
    { nom: "Aït R'Zine" },
    { nom: "Chellata" },
    { nom: "Melbou" },
    { nom: "Tamokra" },
    { nom: "Toudja" },
    { nom: "Sidi Aïch" },
    { nom: "Taourirt Ighil" },
    { nom: "Akfadou" },
    { nom: "Beni Djellil" },
    { nom: "Beni Mehliches" },
    { nom: "Ighram" },
    { nom: "Mellala" },
    { nom: "Ouzellaguen" },
    { nom: "Sedouk" },
    { nom: "Seddouk" },
    { nom: "Souk Oufella" },
    { nom: "Taskriout" },
    { nom: "Tifra" },
    { nom: "Tissira" },
    { nom: "Ait Rizine" },
  ],
  "07": [ // Biskra
    { nom: "Biskra", lat: 34.85, lng: 5.7281 },
    { nom: "Tolga", lat: 34.7228, lng: 5.3794 },
    { nom: "Sidi Okba", lat: 34.7453, lng: 5.9028 },
    { nom: "Ouled Djellal", lat: 34.4189, lng: 5.0639 },
    { nom: "El Kantara", lat: 35.2203, lng: 5.7233 },
    { nom: "Zeribet El Oued", lat: 34.7164, lng: 6.7939 },
    { nom: "M'Chounèche", lat: 34.9964, lng: 5.9178 },
    { nom: "El Hadjeb" },
    { nom: "Branis" },
    { nom: "Chetma" },
    { nom: "Bordj Ben Azzouz" },
    { nom: "Djemorah" },
    { nom: "El Feidh" },
    { nom: "Fontaine des Gazelles" },
    { nom: "Lichana" },
    { nom: "Lioua" },
    { nom: "Meziraa" },
    { nom: "Oumache" },
    { nom: "Ras El Miaad" },
    { nom: "Saâda" },
    { nom: "Sidi Khaled" },
    { nom: "Ain Naga" },
    { nom: "Aïn Zaatout" },
    { nom: "Bouchagroun" },
    { nom: "Doucen" },
    { nom: "El Ghrous" },
    { nom: "El Haouch" },
    { nom: "Foughala" },
    { nom: "Khenguet Sidi Nadji" },
    { nom: "Mekhadma" },
    { nom: "Ouled Skini" },
  ],
  "08": [ // Béchar
    { nom: "Béchar", lat: 31.6167, lng: -2.2167 },
    { nom: "Abadla", lat: 31.0181, lng: -2.7261 },
    { nom: "Kenadsa", lat: 31.5564, lng: -2.4358 },
    { nom: "Beni Abbès", lat: 30.1283, lng: -2.1686 },
    { nom: "Igli", lat: 30.4603, lng: -2.2275 },
    { nom: "Lahmar", lat: 31.2967, lng: -2.3194 },
    { nom: "Taghit", lat: 30.8989, lng: -2.0289 },
    { nom: "Meridja" },
    { nom: "Beni Ikhlef" },
    { nom: "Timoudi" },
    { nom: "El Ouata" },
    { nom: "Tamtert" },
    { nom: "Boukais" },
    { nom: "Ouled Khodeir" },
    { nom: "Erg Ferradj" },
  ],
  "09": [ // Blida
    { nom: "Blida", lat: 36.47, lng: 2.8277 },
    { nom: "Boufarik", lat: 36.5722, lng: 2.9139 },
    { nom: "Larbaa", lat: 36.5531, lng: 3.1644 },
    { nom: "Meftah", lat: 36.6183, lng: 3.2253 },
    { nom: "Bougara", lat: 36.5361, lng: 3.0878 },
    { nom: "Chiffa", lat: 36.4614, lng: 2.6528 },
    { nom: "Bouinan", lat: 36.5039, lng: 2.9211 },
    { nom: "Soumaa", lat: 36.5203, lng: 2.9617 },
    { nom: "Oued El Alleug", lat: 36.5272, lng: 2.7839 },
    { nom: "Ben Khellil" },
    { nom: "Beni Tamou" },
    { nom: "Beni Mered" },
    { nom: "Chrea" },
    { nom: "Djouab" },
    { nom: "El Affroun", lat: 36.4667, lng: 2.625 },
    { nom: "El Afroun" },
    { nom: "Hammam Melouane" },
    { nom: "Mouzaia" },
    { nom: "Oued Djer" },
    { nom: "Ouled Yaïch" },
    { nom: "Bni Khellil" },
    { nom: "Guerrouaou" },
    { nom: "Ain Romana" },
  ],
  "10": [ // Bouira
    { nom: "Bouira", lat: 36.3817, lng: 3.9003 },
    { nom: "Aïn Bessem", lat: 36.3086, lng: 3.6769 },
    { nom: "Lakhdaria", lat: 36.5611, lng: 3.5919 },
    { nom: "Sour El Ghozlane", lat: 36.1442, lng: 3.6914 },
    { nom: "M'Chedallah", lat: 36.3658, lng: 3.8211 },
    { nom: "Aïn El Hadjar" },
    { nom: "Bordj Okhriss" },
    { nom: "Dechmia" },
    { nom: "El Adjiba" },
    { nom: "El Asnam" },
    { nom: "El Hachimia" },
    { nom: "El Khabouzia" },
    { nom: "Guerrouma" },
    { nom: "Haïzer" },
    { nom: "Kadiria", lat: 36.5369, lng: 3.6825 },
    { nom: "Maâla" },
    { nom: "Oued El Berdi" },
    { nom: "Raouraoua" },
    { nom: "Ridane" },
    { nom: "Saharidj" },
    { nom: "Taguedit" },
    { nom: "Taghzout" },
    { nom: "Chorfa" },
    { nom: "Aghbalou" },
    { nom: "Aomar" },
    { nom: "Ath Mansour" },
  ],
  "11": [ // Tamanrasset
    { nom: "Tamanrasset", lat: 22.785, lng: 5.5228 },
    { nom: "Abalessa", lat: 22.9925, lng: 4.8533 },
    { nom: "In Salah", lat: 27.1994, lng: 2.4744 },
    { nom: "Tazrouk" },
    { nom: "In Guezzam", lat: 19.5675, lng: 5.7714 },
    { nom: "Tin Zaouatine" },
    { nom: "In Amguel" },
    { nom: "Ideles" },
    { nom: "Foggaret Ez Zoua" },
  ],
  "12": [ // Tébessa
    { nom: "Tébessa", lat: 35.4056, lng: 8.1197 },
    { nom: "Bir El Ater", lat: 34.7467, lng: 7.9269 },
    { nom: "El Aouinet", lat: 35.8617, lng: 8.4314 },
    { nom: "Cheria", lat: 35.2669, lng: 7.3911 },
    { nom: "El Ma Labiod", lat: 35.6978, lng: 8.0017 },
    { nom: "Boukhadra", lat: 35.6739, lng: 8.5414 },
    { nom: "Ouenza", lat: 35.9622, lng: 8.1403 },
    { nom: "Oum Ali" },
    { nom: "El Hammamet" },
    { nom: "El Kouif" },
    { nom: "Negrine" },
    { nom: "Boulhaf Dyr" },
    { nom: "El Ogla" },
    { nom: "Morsott" },
    { nom: "Thlidjene" },
    { nom: "Hammamet" },
    { nom: "Guorriguer" },
    { nom: "Ferkane" },
    { nom: "Bir Dheheb" },
    { nom: "Bekkaria" },
    { nom: "Stah Guentis" },
    { nom: "Ain Zerga" },
  ],
  "13": [ // Tlemcen
    { nom: "Tlemcen", lat: 34.8828, lng: -1.3178 },
    { nom: "Maghnia", lat: 34.8778, lng: -1.7275 },
    { nom: "Ghazaouet", lat: 35.0994, lng: -1.8586 },
    { nom: "Nedroma", lat: 35.0175, lng: -1.7356 },
    { nom: "Beni Saf", lat: 35.3011, lng: -1.3756 },
    { nom: "Remchi", lat: 35.0525, lng: -1.4358 },
    { nom: "Sebdou", lat: 34.6406, lng: -1.3289 },
    { nom: "Mansourah", lat: 34.7997, lng: -1.2597 },
    { nom: "Aïn Fezza" },
    { nom: "Aïn Ghoraba" },
    { nom: "Aïn Kebira" },
    { nom: "Aïn Tala" },
    { nom: "Aïn Youcef" },
    { nom: "Amieur" },
    { nom: "Azails" },
    { nom: "Bab El Assa" },
    { nom: "Beni Bahdel" },
    { nom: "Beni Boussaid" },
    { nom: "Beni Khellad" },
    { nom: "Beni Mester" },
    { nom: "Beni Ouarsous" },
    { nom: "Beni Snous" },
    { nom: "Bouhlou" },
    { nom: "Chetouane" },
    { nom: "El Aricha" },
    { nom: "El Fehoul" },
    { nom: "El Gor" },
    { nom: "Fellaoucene" },
    { nom: "Hammam Boughrara" },
    { nom: "Honaine" },
    { nom: "Marsa Ben M'Hidi" },
    { nom: "Ouled Mimoun" },
    { nom: "Sabra" },
    { nom: "Sidi Djillali" },
    { nom: "Sidi Medjahed" },
    { nom: "Souani" },
    { nom: "Souk Tlata" },
    { nom: "Terny Beni Hediel" },
    { nom: "Zenata" },
  ],
  "14": [ // Tiaret
    { nom: "Tiaret", lat: 35.3713, lng: 1.3217 },
    { nom: "Sougueur", lat: 35.1875, lng: 1.4917 },
    { nom: "Ksar Chellala", lat: 35.1856, lng: 2.3147 },
    { nom: "Frenda", lat: 35.0706, lng: 1.0428 },
    { nom: "Aïn Kermes" },
    { nom: "Medrissa" },
    { nom: "Rahouia" },
    { nom: "Hamadia" },
    { nom: "Mechraa Safa" },
    { nom: "Oued Lili" },
    { nom: "Takhmaret" },
    { nom: "Sidi Bakhti" },
    { nom: "Dahmouni" },
    { nom: "Aïn Deheb" },
    { nom: "Tousnina" },
    { nom: "Medroussa" },
    { nom: "Chehaïmia" },
    { nom: "Sebt" },
    { nom: "Sidi Hosni" },
    { nom: "Zmalet El Emir Abdelkader" },
    { nom: "Tagdempt" },
    { nom: "Ain Zarit" },
    { nom: "Bougara" },
    { nom: "Guertoufa" },
    { nom: "Mahdia" },
    { nom: "Mellakou" },
    { nom: "Merhana" },
    { nom: "Nahr Ouassel" },
    { nom: "Oued Lilli" },
    { nom: "Rechaïga" },
    { nom: "Serghine" },
    { nom: "Sidi Ali Mellal" },
    { nom: "Tirein" },
    { nom: "Tchikounda" },
  ],
  "15": [ // Tizi Ouzou
    { nom: "Tizi Ouzou", lat: 36.7169, lng: 4.0497 },
    { nom: "Draa Ben Khedda", lat: 36.7314, lng: 3.9642 },
    { nom: "Azazga", lat: 36.7681, lng: 4.3672 },
    { nom: "Boghni", lat: 36.5297, lng: 3.9578 },
    { nom: "Ouadhias", lat: 36.5481, lng: 4.2086 },
    { nom: "Larbaa Nath Irathen", lat: 36.7381, lng: 4.2133 },
    { nom: "Tigzirt", lat: 36.8908, lng: 4.1211 },
    { nom: "Aïn El Hammam", lat: 36.5606, lng: 4.3094 },
    { nom: "Aïn Zaouia" },
    { nom: "Aït Aggouacha" },
    { nom: "Aït Bouaddou" },
    { nom: "Aït Mahmoud" },
    { nom: "Aït Yahia" },
    { nom: "Aït Yahia Moussa" },
    { nom: "Akbil" },
    { nom: "Ath Zikki" },
    { nom: "Azeffoun", lat: 36.8989, lng: 4.4239 },
    { nom: "Beni Aïssou" },
    { nom: "Beni Douala" },
    { nom: "Beni Yenni" },
    { nom: "Beni Zmenzer" },
    { nom: "Bouzeguène" },
    { nom: "Bou Nouh" },
    { nom: "Draa El Mizan", lat: 36.5281, lng: 3.8231 },
    { nom: "Frikat" },
    { nom: "Iboudraren" },
    { nom: "Iferhounène" },
    { nom: "Iflissen" },
    { nom: "Ighil Ali" },
    { nom: "Illilten" },
    { nom: "Imsouhel" },
    { nom: "Imsouhal" },
    { nom: "Irdjen" },
    { nom: "Larbaâ Nath Irathen" },
    { nom: "M'Kira" },
    { nom: "Makouda" },
    { nom: "Mekla" },
    { nom: "Mizrana" },
    { nom: "Ouacif" },
    { nom: "Ouaguenoun" },
    { nom: "Si Mustapha" },
    { nom: "Souama" },
    { nom: "Taddert" },
    { nom: "Tifra" },
    { nom: "Timizart" },
    { nom: "Tirmitine" },
    { nom: "Tizi Gheniff" },
    { nom: "Tizi Rached" },
    { nom: "Yatafen" },
    { nom: "Zekri" },
  ],
  "16": [ // Alger
    { nom: "Alger Centre", lat: 36.7372, lng: 3.0877 },
    { nom: "Bab El Oued", lat: 36.7814, lng: 3.0572 },
    { nom: "Hussein Dey", lat: 36.7464, lng: 3.1156 },
    { nom: "El Harrach", lat: 36.7189, lng: 3.1322 },
    { nom: "Bir Mourad Raïs", lat: 36.7347, lng: 3.0572 },
    { nom: "Rouiba", lat: 36.7378, lng: 3.2772 },
    { nom: "Reghaia", lat: 36.7294, lng: 3.3467 },
    { nom: "Chéraga", lat: 36.7672, lng: 2.9578 },
    { nom: "Birkhadem", lat: 36.7147, lng: 3.0561 },
    { nom: "Kouba", lat: 36.7278, lng: 3.0969 },
    { nom: "Dar El Beida", lat: 36.6994, lng: 3.2194 },
    { nom: "Baraki", lat: 36.6889, lng: 3.1061 },
    { nom: "Aïn Taya", lat: 36.7875, lng: 3.3272 },
    { nom: "Bab Ezzouar", lat: 36.7211, lng: 3.1789 },
    { nom: "Bachdjerrah" },
    { nom: "Ben Aknoun", lat: 36.7561, lng: 3.0219 },
    { nom: "Beni Messous" },
    { nom: "Birtouta" },
    { nom: "Bouzareah", lat: 36.7919, lng: 3.0264 },
    { nom: "Bourouba" },
    { nom: "Casbah" },
    { nom: "Dely Ibrahim", lat: 36.7372, lng: 2.9961 },
    { nom: "Douera" },
    { nom: "Draria" },
    { nom: "El Biar", lat: 36.7667, lng: 3.025 },
    { nom: "El Khroub" },
    { nom: "El Madania" },
    { nom: "El Marsa" },
    { nom: "Es Senia" },
    { nom: "Eucalyptus" },
    { nom: "Hammamet" },
    { nom: "Hydra", lat: 36.7533, lng: 3.0467 },
    { nom: "Khraicia" },
    { nom: "Les Eucalyptus" },
    { nom: "Mahelma" },
    { nom: "Mohamed Hadef" },
    { nom: "Mohammadia" },
    { nom: "Oued Koriche" },
    { nom: "Ouled Chebel" },
    { nom: "Ouled Fayet" },
    { nom: "Raïs Hamidou" },
    { nom: "Sahel" },
    { nom: "Sidi Abdellah" },
    { nom: "Sidi M'Hamed" },
    { nom: "Souidania" },
    { nom: "Staoueli" },
    { nom: "Tessala El Merdja" },
    { nom: "Tipaza" },
    { nom: "Zeralda", lat: 36.7022, lng: 2.8578 },
  ],
  "17": [ // Djelfa
    { nom: "Djelfa", lat: 34.6711, lng: 3.2631 },
    { nom: "Aïn Oussera", lat: 35.4517, lng: 2.9056 },
    { nom: "Messaad", lat: 34.1569, lng: 3.5003 },
    { nom: "Sidi Ladjel" },
    { nom: "Zaâfrane" },
    { nom: "M'Liliha" },
    { nom: "El Idrissia", lat: 35.1989, lng: 3.0933 },
    { nom: "Birine" },
    { nom: "Charef" },
    { nom: "El Guedid" },
    { nom: "Faidh El Botma" },
    { nom: "Had-Sahary" },
    { nom: "Hassi Bahbah" },
    { nom: "Hassi El Euch" },
    { nom: "Moudjebara" },
    { nom: "Oum Laadham" },
    { nom: "Sed Rahal" },
    { nom: "Selmane" },
    { nom: "Sidi Baizid" },
    { nom: "Ain Chouhada" },
    { nom: "Ain El Ibel" },
    { nom: "Ain Maabed" },
    { nom: "Ben Chaabane" },
    { nom: "Bouira Lahdab" },
    { nom: "Dar Chioukh" },
    { nom: "Deldoul" },
    { nom: "Douis" },
    { nom: "El Kheither" },
    { nom: "Guernini" },
    { nom: "Guettara" },
    { nom: "Hassi Fedoul" },
    { nom: "Zaouia El Abidia" },
  ],
  "18": [ // Jijel
    { nom: "Jijel", lat: 36.8194, lng: 5.7658 },
    { nom: "Taher", lat: 36.7711, lng: 5.9 },
    { nom: "El Milia", lat: 36.7494, lng: 6.2628 },
    { nom: "Ziama Mansouriah", lat: 36.8833, lng: 5.5667 },
    { nom: "Aouana", lat: 36.8375, lng: 5.625 },
    { nom: "Chekfa", lat: 36.7486, lng: 6.0458 },
    { nom: "Selma Benziada" },
    { nom: "Eraguène" },
    { nom: "El Ancer" },
    { nom: "Texenna" },
    { nom: "Settara" },
    { nom: "Bordj T'Har" },
    { nom: "Ouled Rabah" },
    { nom: "Ghebala" },
    { nom: "El Aouana" },
    { nom: "Emir Abdelkader" },
    { nom: "Boudriaa Ben Yadjis" },
    { nom: "Bouraoui Belhadef" },
    { nom: "Chahna" },
    { nom: "El Kennar Nouchfi" },
    { nom: "Kaous" },
    { nom: "Oued Adjoul" },
    { nom: "Ouled Yahia Khedrouche" },
    { nom: "Sidi Abdelaziz" },
    { nom: "Sidi Maarouf" },
    { nom: "Tassoust" },
    { nom: "Kheïri Oued Adjoul" },
  ],
  "19": [ // Sétif
    { nom: "Sétif", lat: 36.1911, lng: 5.4114 },
    { nom: "Aïn Oulmène", lat: 35.9114, lng: 5.2992 },
    { nom: "El Eulma", lat: 36.1497, lng: 5.6883 },
    { nom: "Aïn El Kebira", lat: 36.3656, lng: 5.5006 },
    { nom: "Hammam Guergour", lat: 36.2997, lng: 5.3153 },
    { nom: "Salah Bey" },
    { nom: "Babor" },
    { nom: "Beidha Bordj" },
    { nom: "Beni Aziz" },
    { nom: "Beni Chebana" },
    { nom: "Beni Fouda" },
    { nom: "Beni Hocine" },
    { nom: "Beni Ourtilane" },
    { nom: "Bir El Arch" },
    { nom: "Bougaâ", lat: 36.3369, lng: 5.0986 },
    { nom: "Boutaleb" },
    { nom: "Chelata" },
    { nom: "Dehamcha" },
    { nom: "El Ouricia" },
    { nom: "Guellal" },
    { nom: "Guenzet" },
    { nom: "Guidjel" },
    { nom: "Hafir" },
    { nom: "Hammam Soukhna" },
    { nom: "Hamma Bouziane" },
    { nom: "Maâoune" },
    { nom: "Mezloug" },
    { nom: "Ouled Addouane" },
    { nom: "Ouled Si Ahmed" },
    { nom: "Ouled Tebbane" },
    { nom: "Rasfa" },
    { nom: "Serdj El Ghoul" },
    { nom: "Tachouda" },
    { nom: "Talaifacene" },
    { nom: "Taya" },
    { nom: "Tella" },
    { nom: "Terrai Bainen" },
    { nom: "Ain Arnat" },
    { nom: "Ain Lahdjar" },
    { nom: "Ain Legradj" },
    { nom: "Ain Roua" },
    { nom: "Ain Sebt" },
    { nom: "Ain Abessa" },
    { nom: "Aïn Azel" },
    { nom: "Aïn El Kebira" },
    { nom: "Allelick" },
    { nom: "Amoucha" },
    { nom: "Aït Naoual Mezada" },
    { nom: "Beni Mouhli" },
    { nom: "Draa Kebila" },
    { nom: "El Bez" },
    { nom: "El Ouldja" },
    { nom: "Guelta Zerga" },
    { nom: "Ksar El Abtal" },
    { nom: "Maoklane" },
    { nom: "Ouled Sabor" },
    { nom: "Tizi N'Bechar" },
  ],
  "20": [ // Saïda
    { nom: "Saïda", lat: 34.8297, lng: 0.1536 },
    { nom: "Aïn El Hadjar", lat: 34.7917, lng: 0.1547 },
    { nom: "Sidi Boubekeur", lat: 34.7994, lng: 0.1533 },
    { nom: "El Hassasna" },
    { nom: "Ouled Khaled" },
    { nom: "Sidi Ahmed" },
    { nom: "El Braria" },
    { nom: "Aïn Sekhouna" },
    { nom: "El Moulay" },
    { nom: "Aïn Soltane" },
    { nom: "Doui Tabet" },
    { nom: "Hounet" },
    { nom: "Maamoura" },
    { nom: "Moulay Larbi" },
    { nom: "Tircine" },
    { nom: "Youb" },
  ],
  "21": [ // Skikda
    { nom: "Skikda", lat: 36.876, lng: 6.9069 },
    { nom: "Azzaba", lat: 36.7417, lng: 7.1039 },
    { nom: "Collo", lat: 37.0031, lng: 6.5639 },
    { nom: "El Harrouch", lat: 36.8014, lng: 7.0442 },
    { nom: "Tamalous", lat: 36.8492, lng: 6.6361 },
    { nom: "Ramdane Djamel", lat: 36.8833, lng: 6.8717 },
    { nom: "El Hadaïek" },
    { nom: "Aïn Zouit" },
    { nom: "Beni Bechir" },
    { nom: "Beni Zid" },
    { nom: "Bouchtata" },
    { nom: "Cheraia" },
    { nom: "Djendel Saadi Mohamed" },
    { nom: "Emdjez Edchich" },
    { nom: "Es Sebt" },
    { nom: "Filfila" },
    { nom: "Kerkera" },
    { nom: "Khelil" },
    { nom: "Oued El Aneb" },
    { nom: "Oued Zhour" },
    { nom: "Ouled Attia" },
    { nom: "Ouled Hbaba" },
    { nom: "Sidi Mezghiche" },
    { nom: "Saf Saf" },
    { nom: "Salah Bouchaour" },
    { nom: "Ain Bouziane" },
    { nom: "Ben Azzouz" },
    { nom: "Béni Oulbane" },
    { nom: "El Ghedir" },
    { nom: "Hamadi Krouma" },
    { nom: "Zerdazas" },
    { nom: "Zitouna" },
  ],
  "22": [ // Sidi Bel Abbès
    { nom: "Sidi Bel Abbès", lat: 35.1897, lng: -0.6297 },
    { nom: "Tessala", lat: 35.2375, lng: -0.7611 },
    { nom: "Telagh", lat: 34.7814, lng: -0.5703 },
    { nom: "Moulay Slissen", lat: 34.9722, lng: -0.3378 },
    { nom: "Aïn Trid" },
    { nom: "Marhoum", lat: 34.4428, lng: -0.1858 },
    { nom: "Sfisef" },
    { nom: "Bedrabine El Mokrani" },
    { nom: "Ben Badis" },
    { nom: "Mezaourou" },
    { nom: "Sidi Brahim" },
    { nom: "Sidi Hamadouche" },
    { nom: "Sidi Khaled" },
    { nom: "Ain El Berd", lat: 35.3697, lng: -0.5228 },
    { nom: "Ben Lahcene" },
    { nom: "Benyahia Abderrahmane" },
    { nom: "Boudjebha El Bordj" },
    { nom: "Boukhanafis" },
    { nom: "El Haçaiba" },
    { nom: "Hassi Dahou" },
    { nom: "Hassi Zahana" },
    { nom: "Lamtar" },
    { nom: "Mcid" },
    { nom: "Merine" },
    { nom: "Mostefa Benbrahim" },
    { nom: "Oued Sebaa" },
    { nom: "Oued Taourira" },
    { nom: "Ras El Ma" },
    { nom: "Redjem Demouche" },
    { nom: "Sehala Thaoura" },
    { nom: "Sidi Ali Boussidi" },
    { nom: "Sidi Ali Benyoub" },
    { nom: "Sidi Chaib" },
    { nom: "Sidi Dahou Des Zairs" },
    { nom: "Sidi Daho El Zairs" },
    { nom: "Tenira" },
    { nom: "Tilmouni" },
    { nom: "Zerouala" },
  ],
  "23": [ // Annaba
    { nom: "Annaba", lat: 36.9, lng: 7.7667 },
    { nom: "Berrahal", lat: 36.8406, lng: 7.5242 },
    { nom: "El Bouni", lat: 36.8711, lng: 7.7553 },
    { nom: "El Hadjar", lat: 36.8122, lng: 7.7294 },
    { nom: "Aïn Berda", lat: 36.6486, lng: 7.5394 },
    { nom: "Chetaïbi", lat: 37.0642, lng: 7.2267 },
    { nom: "Eulma" },
    { nom: "Oued El Aneb" },
    { nom: "Seraidi", lat: 36.9267, lng: 7.6569 },
    { nom: "Sidi Amar", lat: 36.8281, lng: 7.7019 },
    { nom: "Tréat" },
    { nom: "Cheurfa" },
    { nom: "Kherraza" },
  ],
  "24": [ // Guelma
    { nom: "Guelma", lat: 36.4647, lng: 7.4306 },
    { nom: "Bouchegouf", lat: 36.4797, lng: 7.7167 },
    { nom: "Oued Zenati", lat: 36.3392, lng: 7.2536 },
    { nom: "Héliopolis", lat: 36.5317, lng: 7.4917 },
    { nom: "Aïn Makhlouf", lat: 36.2958, lng: 7.2194 },
    { nom: "Hammam Debagh", lat: 36.4386, lng: 7.3722 },
    { nom: "Aïn Ben Beida" },
    { nom: "Aïn Larbi" },
    { nom: "Aïn Regada" },
    { nom: "Aïn Sandel" },
    { nom: "Belkheir" },
    { nom: "Ben Djarah" },
    { nom: "Bordj Sabat" },
    { nom: "Bouati Mahmoud" },
    { nom: "Djebala Khemissa" },
    { nom: "El Fedjoudj" },
    { nom: "Guelaat Bou Sbaa" },
    { nom: "Hammam N'Bails" },
    { nom: "Khezaras" },
    { nom: "M'Raou" },
    { nom: "Medjez Amar" },
    { nom: "Medjez Sfa" },
    { nom: "Nechmaya" },
    { nom: "Oued Fragha" },
    { nom: "Ras El Agba" },
    { nom: "Sellaoua Announa" },
    { nom: "Tamlouka" },
  ],
  "25": [ // Constantine
    { nom: "Constantine", lat: 36.365, lng: 6.6147 },
    { nom: "El Khroub", lat: 36.2711, lng: 6.6911 },
    { nom: "Aïn Smara", lat: 36.1975, lng: 6.5211 },
    { nom: "Didouche Mourad", lat: 36.4517, lng: 6.6361 },
    { nom: "Hamma Bouziane", lat: 36.4153, lng: 6.5772 },
    { nom: "Zighoud Youcef", lat: 36.5183, lng: 6.7128 },
    { nom: "Beni Hamidane" },
    { nom: "Ibn Badis" },
    { nom: "Ibn Ziad" },
    { nom: "Messaoud Boudjeriou" },
    { nom: "Ouled Rahmoune" },
  ],
  "26": [ // Médéa
    { nom: "Médéa", lat: 36.2647, lng: 2.7528 },
    { nom: "Ksar El Boukhari", lat: 35.8814, lng: 2.7458 },
    { nom: "Aïn Boucif", lat: 35.9033, lng: 3.2019 },
    { nom: "Berrouaghia", lat: 36.1317, lng: 2.9144 },
    { nom: "Tablat", lat: 36.4272, lng: 3.3283 },
    { nom: "Beni Slimane", lat: 36.3317, lng: 3.2889 },
    { nom: "El Azizia" },
    { nom: "El Omaria" },
    { nom: "Mezghenna" },
    { nom: "Si Mahdjoub" },
    { nom: "Sidi Naâmane" },
    { nom: "Ouamri" },
    { nom: "Derrag" },
    { nom: "El Hamdania" },
    { nom: "Ain Boucif" },
    { nom: "Ain Ouksir" },
    { nom: "Ben Chicao" },
    { nom: "Beni Messaoud" },
    { nom: "Bir Ben Laabed" },
    { nom: "Boghari" },
    { nom: "Bou Aiche" },
    { nom: "Bouaïche" },
    { nom: "Chellalet El Adhaoura" },
    { nom: "Chelalet El Adhaoura" },
    { nom: "Cheniguel" },
    { nom: "Damiat" },
    { nom: "Djouab" },
    { nom: "El Guettar" },
    { nom: "Hannacha" },
    { nom: "Khams Djouamaa" },
    { nom: "Mihoub" },
    { nom: "Oued Harbil" },
    { nom: "Ouled Antar" },
    { nom: "Ouled Brahim" },
    { nom: "Ouled Deïd" },
    { nom: "Ouled Hellal" },
    { nom: "Ouled Maaref" },
    { nom: "Ouzera" },
    { nom: "Rebaia" },
    { nom: "Saneg" },
    { nom: "Sedraia" },
    { nom: "Seghouane" },
    { nom: "Sidi Damed" },
    { nom: "Sidi Zahar" },
    { nom: "Souagui" },
    { nom: "Tafraout" },
    { nom: "Tamesguida" },
    { nom: "Tizi Mahdi" },
    { nom: "Zoubiria" },
  ],
  "27": [ // Mostaganem
    { nom: "Mostaganem", lat: 35.9311, lng: 0.0889 },
    { nom: "Aïn Tedles", lat: 35.8711, lng: 0.2278 },
    { nom: "Aïn Nouissy", lat: 35.8311, lng: 0.1639 },
    { nom: "Mazagran", lat: 35.9039, lng: 0.0664 },
    { nom: "Achacha", lat: 35.7772, lng: 0.1972 },
    { nom: "Bouguirat", lat: 35.7542, lng: 0.0753 },
    { nom: "Sidi Lakhdar", lat: 35.8531, lng: 0.3083 },
    { nom: "Aïn Boudinar" },
    { nom: "Aïn Sidi Cherif" },
    { nom: "Arzoune-El-Had" },
    { nom: "Benabdelmalek Ramdane" },
    { nom: "Blad Touahria" },
    { nom: "Bouguirat" },
    { nom: "El Hassiane" },
    { nom: "Fornaka" },
    { nom: "Hadjadj" },
    { nom: "Hassi Mameche" },
    { nom: "Khadra" },
    { nom: "Kheireddine" },
    { nom: "Mesra" },
    { nom: "Mansourah" },
    { nom: "Nekmaria" },
    { nom: "Ouled Boughalem" },
    { nom: "Ouled Maallah" },
    { nom: "Safsaf" },
    { nom: "Sidi Ali" },
    { nom: "Sidi El Mejdoub" },
    { nom: "Sidi Lakhdar" },
    { nom: "Souaflia" },
    { nom: "Souahlia" },
    { nom: "Tazgait" },
    { nom: "Touahria" },
  ],
  "28": [ // M'Sila
    { nom: "M'Sila", lat: 35.7019, lng: 4.5439 },
    { nom: "Bou Saada", lat: 35.2103, lng: 4.1764 },
    { nom: "Aïn El Melh", lat: 35.7847, lng: 4.1642 },
    { nom: "Magra", lat: 35.8697, lng: 4.7272 },
    { nom: "Sidi Aïssa", lat: 35.8911, lng: 3.7833 },
    { nom: "Berhoum", lat: 35.9197, lng: 4.5939 },
    { nom: "Aïn El Hadjel", lat: 35.6308, lng: 4.3597 },
    { nom: "Khoubana" },
    { nom: "Aïn Fares" },
    { nom: "Aïn Khadra" },
    { nom: "Ben Srour" },
    { nom: "Benzouh" },
    { nom: "Belaiba" },
    { nom: "Bensour" },
    { nom: "Chellal" },
    { nom: "Dehahna" },
    { nom: "Dghoumes" },
    { nom: "El Hamel" },
    { nom: "El Houamed" },
    { nom: "Hammam Dalaa" },
    { nom: "Khettouti Sed El Djir" },
    { nom: "Maadid" },
    { nom: "Medjedel" },
    { nom: "Mhara" },
    { nom: "Mezghrane" },
    { nom: "Mohamed Boudiaf" },
    { nom: "Mtarfa" },
    { nom: "Ouanougha" },
    { nom: "Oued Chair" },
    { nom: "Ouled Addi Guebala" },
    { nom: "Ouled Derradj" },
    { nom: "Ouled Mansour" },
    { nom: "Ouled Masseoud Addi" },
    { nom: "Ouled Slimane" },
    { nom: "Ouled Sidi Ibrahim" },
    { nom: "Sidi Ameur" },
    { nom: "Sidi Hadjeres" },
    { nom: "Sidi M'Hamed" },
    { nom: "Slim" },
    { nom: "Souamaa" },
    { nom: "Tamsa" },
    { nom: "Zarzour" },
  ],
  "29": [ // Mascara
    { nom: "Mascara", lat: 35.3956, lng: 0.1408 },
    { nom: "Sig", lat: 35.5244, lng: -0.1908 },
    { nom: "Tighennif", lat: 35.4253, lng: -0.2869 },
    { nom: "Oued El Abtal", lat: 35.4733, lng: 0.1319 },
    { nom: "Aïn Fares" },
    { nom: "Ghriss", lat: 35.3208, lng: 0.1756 },
    { nom: "Hachem" },
    { nom: "Matemore" },
    { nom: "Chorfa" },
    { nom: "Aouf" },
    { nom: "El Ghomri" },
    { nom: "El Keurt" },
    { nom: "Oggaz", lat: 35.5572, lng: 0.0508 },
    { nom: "Sedjerara" },
    { nom: "Aïn Fekan" },
    { nom: "Beniane" },
    { nom: "Bou Hanifia" },
    { nom: "El Bordj" },
    { nom: "El Guettena" },
    { nom: "El Hachem" },
    { nom: "Ferraguig" },
    { nom: "Froha" },
    { nom: "Gharrous" },
    { nom: "Khalouia" },
    { nom: "Maoussa" },
    { nom: "Mocta Douz" },
    { nom: "Mohammadia" },
    { nom: "Nesmoth" },
    { nom: "Oued Taria" },
    { nom: "Ras El Aïn Amirouche" },
    { nom: "Sidi Abdelmoumen" },
    { nom: "Sidi Boussaid" },
    { nom: "Sidi Kada" },
    { nom: "Tizi" },
    { nom: "Zahana" },
  ],
  "30": [ // Ouargla
    { nom: "Ouargla", lat: 31.9497, lng: 5.3231 },
    { nom: "Hassi Messaoud", lat: 31.6964, lng: 6.0592 },
    { nom: "Touggourt", lat: 33.1, lng: 6.0667 },
    { nom: "Témacine", lat: 33.0636, lng: 5.9864 },
    { nom: "El Hadjira", lat: 32.5086, lng: 5.5406 },
    { nom: "Rouissat" },
    { nom: "Ain El Beïda" },
    { nom: "Blidet Amor" },
    { nom: "El Allia" },
    { nom: "El Borma" },
    { nom: "Megarine" },
    { nom: "N'Goussa" },
    { nom: "Nezla" },
    { nom: "Sidi Khouiled" },
    { nom: "Sidi Slimane" },
    { nom: "Taibet" },
    { nom: "Tamessamet" },
    { nom: "Zaouia El Abidia" },
  ],
  "31": [ // Oran
    { nom: "Oran", lat: 35.6969, lng: -0.6331 },
    { nom: "Es Sénia", lat: 35.6506, lng: -0.6017 },
    { nom: "Bir El Djir", lat: 35.7294, lng: -0.5853 },
    { nom: "Arzew", lat: 35.8306, lng: -0.3175 },
    { nom: "Bethioua", lat: 35.8, lng: -0.25 },
    { nom: "Mers El Kébir", lat: 35.7333, lng: -0.7167 },
    { nom: "Ain El Turk", lat: 35.75, lng: -0.7667 },
    { nom: "El Ancor", lat: 35.75, lng: -0.5 },
    { nom: "Hassi Ben Okba", lat: 35.55, lng: -0.7 },
    { nom: "Sidi Chami", lat: 35.63, lng: -0.59 },
    { nom: "Gdyel", lat: 35.72, lng: -0.52 },
    { nom: "Ben Freha" },
    { nom: "Boufatis" },
    { nom: "Boutlelis" },
    { nom: "Hassi Mefsoukh" },
    { nom: "Oued Tlélat", lat: 35.5769, lng: -0.4536 },
    { nom: "Sidi Ben Yebka" },
    { nom: "Tafraoui" },
    { nom: "Ain Biya" },
  ],
  "32": [ // El Bayadh
    { nom: "El Bayadh", lat: 33.6811, lng: 1.0172 },
    { nom: "Aïn Ouarka" },
    { nom: "Rogassa" },
    { nom: "Bougtob", lat: 33.0583, lng: 1.1156 },
    { nom: "El Abiodh Sidi Cheikh", lat: 32.9056, lng: 0.5333 },
    { nom: "Arbaouat" },
    { nom: "Boualem" },
    { nom: "Brezina" },
    { nom: "Cheguig" },
    { nom: "El Bnoud" },
    { nom: "Ghassoul" },
    { nom: "Kef El Ahmar" },
    { nom: "Mehara" },
    { nom: "Sidi Ameur" },
    { nom: "Sidi Tifour" },
    { nom: "Stitten" },
    { nom: "Tousmouline" },
  ],
  "33": [ // Illizi
    { nom: "Illizi", lat: 26.4844, lng: 8.4828 },
    { nom: "Djanet", lat: 24.5547, lng: 9.4844 },
    { nom: "In Amenas", lat: 28.0514, lng: 9.5481 },
    { nom: "Bordj El Haouès" },
    { nom: "Debdeb" },
  ],
  "34": [ // Bordj Bou Arréridj
    { nom: "Bordj Bou Arréridj", lat: 36.0731, lng: 4.7631 },
    { nom: "Ras El Oued", lat: 35.9483, lng: 5.0353 },
    { nom: "El Main" },
    { nom: "Aïn Taghrout" },
    { nom: "Sidi Embarek" },
    { nom: "El Achir", lat: 36.0639, lng: 4.6211 },
    { nom: "Aïn Tessala El Maneaa" },
    { nom: "Aïn Trik" },
    { nom: "Belimour" },
    { nom: "Ben Daoud" },
    { nom: "Bir Kasdali" },
    { nom: "Bordj Ghedir" },
    { nom: "Bordj Zemmoura" },
    { nom: "Colla" },
    { nom: "Djaafra" },
    { nom: "El Ach" },
    { nom: "El Anseur" },
    { nom: "Ghilassa" },
    { nom: "Hasnaoua" },
    { nom: "Khelil" },
    { nom: "Mansourah" },
    { nom: "Medjana" },
    { nom: "Ouled Braham" },
    { nom: "Ouled Sidi Brahim" },
    { nom: "Rabta" },
    { nom: "Ras El Oued" },
    { nom: "Tassameurt" },
    { nom: "Tefreg" },
    { nom: "Theniet El Nasr" },
  ],
  "35": [ // Boumerdès
    { nom: "Boumerdès", lat: 36.7669, lng: 3.4769 },
    { nom: "Boudouaou", lat: 36.7358, lng: 3.4072 },
    { nom: "Khemis El Khechna", lat: 36.6539, lng: 3.3483 },
    { nom: "Corso", lat: 36.8058, lng: 3.5633 },
    { nom: "Thenia", lat: 36.7222, lng: 3.5569 },
    { nom: "Dellys", lat: 36.9181, lng: 3.9097 },
    { nom: "Afir" },
    { nom: "Aït Amara" },
    { nom: "Ammal" },
    { nom: "Baghlia" },
    { nom: "Ben Choud" },
    { nom: "Beni Amrane" },
    { nom: "Bordj Ménaïel", lat: 36.7444, lng: 3.7194 },
    { nom: "Boudouaou El Bahri" },
    { nom: "Boumerdas" },
    { nom: "Chaâbet El Ameur" },
    { nom: "Djinet" },
    { nom: "El Kharrouba" },
    { nom: "Hammedi" },
    { nom: "Issers" },
    { nom: "Keddara" },
    { nom: "Khemis El Khechna" },
    { nom: "Larbatache" },
    { nom: "Leghata" },
    { nom: "Naciria" },
    { nom: "Ouled Aïssa" },
    { nom: "Ouled Hedadj" },
    { nom: "Ouled Moussa" },
    { nom: "Si Mustapha" },
    { nom: "Souk El Had" },
    { nom: "Tidjelabine" },
    { nom: "Timezrit" },
    { nom: "Zemmouri" },
  ],
  "36": [ // El Tarf
    { nom: "El Tarf", lat: 36.7667, lng: 8.3156 },
    { nom: "Ben Mehidi", lat: 36.8181, lng: 8.3333 },
    { nom: "Besbes", lat: 36.9, lng: 7.9167 },
    { nom: "Aïn El Assel", lat: 36.8042, lng: 8.1917 },
    { nom: "Drean", lat: 36.6853, lng: 7.7514 },
    { nom: "El Kala", lat: 36.8958, lng: 8.4439 },
    { nom: "Bouteldja" },
    { nom: "Chebaïta Mokhtar" },
    { nom: "Cheffia" },
    { nom: "Echatt" },
    { nom: "El Aioun" },
    { nom: "Hammam Beni Salah" },
    { nom: "Lac des Oiseaux" },
    { nom: "Oum Teboul" },
    { nom: "Ramel Souk" },
    { nom: "Souarekh" },
    { nom: "Zerizer" },
    { nom: "Zitouna" },
  ],
  "37": [ // Tindouf
    { nom: "Tindouf", lat: 27.6742, lng: -8.1478 },
    { nom: "Oum El Assel" },
  ],
  "38": [ // Tissemsilt
    { nom: "Tissemsilt", lat: 35.6072, lng: 1.8117 },
    { nom: "Khemisti", lat: 35.7342, lng: 2.0017 },
    { nom: "Sidi Boutouchent" },
    { nom: "Bordj Bou Naama" },
    { nom: "Lazharia" },
    { nom: "Beni Chaib" },
    { nom: "Boucaid" },
    { nom: "Boudouaou El Bahri" },
    { nom: "Ouled Bessem" },
    { nom: "Sidi Slimane" },
    { nom: "Tamalaht" },
    { nom: "Theniet El Had" },
    { nom: "Youssoufia" },
    { nom: "Ammari" },
    { nom: "Beni Lahcene" },
    { nom: "Layoune" },
    { nom: "Lardjem" },
    { nom: "Maasem" },
    { nom: "Melaab" },
    { nom: "Ouled Bessem" },
    { nom: "Sidi Abed" },
    { nom: "Sidi Lantri" },
  ],
  "39": [ // El Oued
    { nom: "El Oued", lat: 33.3672, lng: 6.8628 },
    { nom: "Robbah", lat: 33.2908, lng: 6.8819 },
    { nom: "Guemar", lat: 33.4864, lng: 6.7803 },
    { nom: "Kouinine", lat: 33.4672, lng: 6.9083 },
    { nom: "Reguiba", lat: 33.0028, lng: 6.6917 },
    { nom: "Djamaa", lat: 33.5358, lng: 5.9922 },
    { nom: "Bayadha" },
    { nom: "Debila" },
    { nom: "Douar El Maa" },
    { nom: "El Ogla" },
    { nom: "El Reguiba" },
    { nom: "Hamraia" },
    { nom: "Hassani Abdelkrim" },
    { nom: "Magrane" },
    { nom: "Mih Ouensa" },
    { nom: "Nakhla" },
    { nom: "Oued El Alenda" },
    { nom: "Ourmas" },
    { nom: "Sidi Aoun" },
    { nom: "Sidi Khalil" },
    { nom: "Still" },
    { nom: "Taghzout" },
    { nom: "Taleb Larbi" },
    { nom: "Trifaoui" },
  ],
  "40": [ // Khenchela
    { nom: "Khenchela", lat: 35.4286, lng: 7.1431 },
    { nom: "Aïn Touila", lat: 35.3889, lng: 7.3028 },
    { nom: "Baghaï", lat: 35.6039, lng: 7.2736 },
    { nom: "Chechar", lat: 35.2167, lng: 6.8667 },
    { nom: "El Mahmal" },
    { nom: "Kaïs" },
    { nom: "Khirane" },
    { nom: "M'Sara" },
    { nom: "Ouled Rechache" },
    { nom: "Remila" },
    { nom: "Taouzient" },
  ],
  "41": [ // Souk Ahras
    { nom: "Souk Ahras", lat: 36.2864, lng: 7.9508 },
    { nom: "Sedrata", lat: 36.1239, lng: 7.7339 },
    { nom: "Mechroha", lat: 36.4236, lng: 8.1978 },
    { nom: "Bir Bouhouche" },
    { nom: "Ragouba" },
    { nom: "Aïn Soltane" },
    { nom: "Aïn Zana" },
    { nom: "Drea" },
    { nom: "El Ksar" },
    { nom: "Haddada" },
    { nom: "Hanancha" },
    { nom: "Khedara" },
    { nom: "Khemissa" },
    { nom: "Mdaourouche" },
    { nom: "Merahna" },
    { nom: "Oued El Kebrit" },
    { nom: "Oum El Adhaim" },
    { nom: "Safel El Ouiden" },
    { nom: "Taoura" },
    { nom: "Terraguelt" },
    { nom: "Zaarouria" },
  ],
  "42": [ // Tipaza
    { nom: "Tipaza", lat: 36.5894, lng: 2.4483 },
    { nom: "Koléa", lat: 36.6394, lng: 2.7647 },
    { nom: "Cherchell", lat: 36.6069, lng: 2.1931 },
    { nom: "Hadjout", lat: 36.5106, lng: 2.5267 },
    { nom: "Bou Ismail", lat: 36.6411, lng: 2.6928 },
    { nom: "Marengo" },
    { nom: "Aïn Tagourait" },
    { nom: "Aghbal" },
    { nom: "Aïn Benian" },
    { nom: "Attatba" },
    { nom: "Bou Haroun" },
    { nom: "Bourkika" },
    { nom: "Chaïba" },
    { nom: "Damous" },
    { nom: "El Nador" },
    { nom: "Fouka", lat: 36.6778, lng: 2.6961 },
    { nom: "Gouraya" },
    { nom: "Hadjout" },
    { nom: "Khemisti" },
    { nom: "Larhat" },
    { nom: "Meurad" },
    { nom: "Menaceur" },
    { nom: "Messelmoun" },
    { nom: "Nador" },
    { nom: "Sidi Amar" },
    { nom: "Sidi Ghiles" },
    { nom: "Sidi Rached" },
    { nom: "Sidi Semiane" },
    { nom: "Tessala El Merdja" },
    { nom: "Tipasa" },
  ],
  "43": [ // Mila
    { nom: "Mila", lat: 36.4508, lng: 6.2636 },
    { nom: "Ferdjioua", lat: 36.4, lng: 6.0833 },
    { nom: "Chelghoum Laïd", lat: 36.1817, lng: 6.1708 },
    { nom: "Grarem Gouga", lat: 36.5467, lng: 6.3836 },
    { nom: "Aïn Mellouk" },
    { nom: "Ahmed Rachedi" },
    { nom: "Aïn Beida Harriche" },
    { nom: "Aïn Tine" },
    { nom: "Amira Arrès" },
    { nom: "Benyahia Abderrahmane" },
    { nom: "Bouhatem" },
    { nom: "El Mechira" },
    { nom: "Hamala" },
    { nom: "Minar Zarza" },
    { nom: "Oued Athmenia" },
    { nom: "Oued El Athmania" },
    { nom: "Oued Seguen" },
    { nom: "Rouached" },
    { nom: "Sidi Khelifa" },
    { nom: "Sidi Merouane" },
    { nom: "Tadjenanet" },
    { nom: "Teleghma" },
    { nom: "Terrai Baïnen" },
    { nom: "Tessala Lemtaï" },
    { nom: "Tassadane Haddada" },
    { nom: "Yahia Beni Guecha" },
    { nom: "Zeghai" },
  ],
  "44": [ // Aïn Defla
    { nom: "Aïn Defla", lat: 36.2644, lng: 1.9661 },
    { nom: "Miliana", lat: 36.2997, lng: 2.2333 },
    { nom: "Khemis Miliana", lat: 36.2619, lng: 2.2183 },
    { nom: "Aïn Lechiakh" },
    { nom: "Djendel", lat: 36.2008, lng: 2.4194 },
    { nom: "El Attaf", lat: 36.2175, lng: 1.7358 },
    { nom: "El Abadia" },
    { nom: "El Amra" },
    { nom: "Hammam Righa" },
    { nom: "Hoceinia" },
    { nom: "Ain Benian" },
    { nom: "Ain Soltane" },
    { nom: "Ain Torki" },
    { nom: "Birbouche" },
    { nom: "Bordj Emir Khaled" },
    { nom: "Boumedfaa" },
    { nom: "Bourached" },
    { nom: "El Hassania" },
    { nom: "El Main" },
    { nom: "Jemaa Ouled Chikh" },
    { nom: "Mekhatria" },
    { nom: "Oued Chorfa" },
    { nom: "Oued Djemaa" },
    { nom: "Oued El Djemaa" },
    { nom: "Rouina" },
    { nom: "Sidi Lakhdar" },
    { nom: "Tarik Ibn Ziad" },
    { nom: "Tiberkanine" },
    { nom: "Zeddine" },
    { nom: "Bir Ould Khelifa" },
    { nom: "Boumedfaa" },
  ],
  "45": [ // Naâma
    { nom: "Naâma", lat: 33.2683, lng: -0.3081 },
    { nom: "Mecheria", lat: 33.5542, lng: -0.2831 },
    { nom: "Aïn Sefra", lat: 32.7511, lng: -0.5919 },
    { nom: "Sfissifa" },
    { nom: "Moghrar", lat: 32.5422, lng: -0.5831 },
    { nom: "Aïn Ben Khelil" },
    { nom: "Asla" },
    { nom: "Kasdir" },
    { nom: "Mekmen Ben Amar" },
  ],
  "46": [ // Aïn Témouchent
    { nom: "Aïn Témouchent", lat: 35.2994, lng: -1.1403 },
    { nom: "Hammam Bou Hadjar", lat: 35.3792, lng: -0.9556 },
    { nom: "Beni Saf", lat: 35.3011, lng: -1.3756 },
    { nom: "El Amria", lat: 35.5333, lng: -1.0167 },
    { nom: "Aïn El Arba" },
    { nom: "Aïn Kihal" },
    { nom: "Aïn Larbaa" },
    { nom: "Aïn Tolba" },
    { nom: "Aoubellil" },
    { nom: "Beni Saf" },
    { nom: "Chentouf" },
    { nom: "El Emir Abdelkader" },
    { nom: "El Malah" },
    { nom: "Es Senia" },
    { nom: "Hassasna" },
    { nom: "Messaid" },
    { nom: "Oulhaça El Gheraba" },
    { nom: "Oued Berkeche" },
    { nom: "Oued Sebbah" },
    { nom: "Ouled Boudjemaa" },
    { nom: "Ouled Kihal" },
    { nom: "Sidi Ben Adda" },
    { nom: "Sidi Boumediene" },
    { nom: "Sidi Safi" },
    { nom: "Tadmaia" },
    { nom: "Terga" },
  ],
  "47": [ // Ghardaïa
    { nom: "Ghardaïa", lat: 32.4911, lng: 3.6736 },
    { nom: "Metlili", lat: 32.2658, lng: 3.6242 },
    { nom: "El Ménéa", lat: 30.5758, lng: 2.8797 },
    { nom: "Berriane", lat: 32.8272, lng: 3.7736 },
    { nom: "Guerrara", lat: 32.7953, lng: 4.4311 },
    { nom: "Bounoura" },
    { nom: "Dhayet Bendhahoua" },
    { nom: "El Atteuf" },
    { nom: "Mansoura" },
    { nom: "Mermite" },
    { nom: "Sebseb" },
    { nom: "Zelfana" },
  ],
  "48": [ // Relizane
    { nom: "Relizane", lat: 35.7358, lng: 0.5561 },
    { nom: "Mazouna", lat: 35.9833, lng: 0.6 },
    { nom: "Oued Rhiou", lat: 35.9658, lng: 0.9336 },
    { nom: "Yellel" },
    { nom: "Aïn Tarek" },
    { nom: "Amoura" },
    { nom: "Bendaoud" },
    { nom: "Beni Dergoun" },
    { nom: "Beni Zentis" },
    { nom: "Dar Ben Abdellah" },
    { nom: "El Guettar" },
    { nom: "El Hamadna" },
    { nom: "El Hassi" },
    { nom: "El Matmar" },
    { nom: "Hamri" },
    { nom: "Kalaa" },
    { nom: "Lahlef" },
    { nom: "Mediouna" },
    { nom: "Mendes" },
    { nom: "Oued El Djemaa" },
    { nom: "Ramka" },
    { nom: "Sidi Khettab" },
    { nom: "Sidi Lazreug" },
    { nom: "Sidi M'Hamed Ben Ali" },
    { nom: "Sidi Saada" },
    { nom: "Souk El Had" },
    { nom: "Zemmora" },
  ],
}
