// ════════════════════════════════════════════════════════════════════════════
// Source officielle : Journal Officiel de la République Algérienne N°47,
// 12 Dhou El Hidja 1443 — 11 juillet 2022
// 58 maladies à déclaration obligatoire (MDO)
// ════════════════════════════════════════════════════════════════════════════

export const MALADIES_SEED = [

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 1 — Surveillance nationale (44 maladies)
  // ══════════════════════════════════════════════════════════════════════════

  // ─── Déclaration en urgence (< 4h + appel téléphonique) ──────────────────

  {
    nom: "Infections à bactéries multi-résistantes (BMR)",
    codeCim10: "U82",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "BMR",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: false,
  },
  {
    nom: "Infections du site opératoire (ISO)",
    codeCim10: "Y62",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "ISO",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: false,
  },
  {
    nom: "Méningite à haemophilus influenzae b",
    codeCim10: "G000",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Méningite Hib",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "meningite",
  },
  {
    nom: "Méningites à méningocoque",
    codeCim10: "G01A39",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Méningite méning.",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "meningite",
  },
  {
    nom: "Méningite à pneumocoque",
    codeCim10: "G01",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Méningite pneumo",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "meningite",
  },
  {
    nom: "Méningites virales",
    codeCim10: "G03",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Méningite virale",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "meningite",
  },
  {
    nom: "Méningo-encéphalites virales",
    codeCim10: "G05",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Méningo-encéph.",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: false,
  },
  {
    nom: "Paludisme",
    codeCim10: "B54",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "Paludisme",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: false,
  },
  {
    nom: "Paralysie flasque aiguë (PFA)",
    codeCim10: "G82",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "PFA",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "pfa",
  },
  {
    nom: "Pneumopathie acquise sous ventilation mécanique",
    codeCim10: "J95",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "urgence",
    nomCourt: "PAVM",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: false,
  },

  // ─── Déclaration quotidienne (24h) ────────────────────────────────────────

  {
    nom: "Botulisme",
    codeCim10: "A05.1",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Botulisme",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Brucellose",
    codeCim10: "A23",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Brucellose",
    seuilDefaut: 5,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Charbon",
    codeCim10: "A22",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Charbon",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Coqueluche",
    codeCim10: "A37",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Coqueluche",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Diphtérie",
    codeCim10: "A36",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Diphtérie",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "diphterie",
  },
  {
    nom: "Dysenterie amibienne et bacillaire",
    codeCim10: "A06",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Dysenterie",
    seuilDefaut: 10,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Echinococcose (Kyste hydatique)",
    codeCim10: "B67",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Kyste hydatique",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Fièvre typhoïde et paratyphoïde",
    codeCim10: "A01",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Typhoïde",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Hépatite virale A",
    codeCim10: "B15",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Hépatite A",
    seuilDefaut: 10,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Légionellose",
    codeCim10: "A48",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Légionellose",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Leishmaniose cutanée",
    codeCim10: "B551",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Leish. cutanée",
    seuilDefaut: 10,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Leishmaniose viscérale",
    codeCim10: "B550",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Leish. viscérale",
    seuilDefaut: 3,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Lèpre",
    codeCim10: "A30",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Lèpre",
    seuilDefaut: 1,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Leptospirose",
    codeCim10: "A27",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Leptospirose",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Listériose",
    codeCim10: "A32",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Listériose",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Peste",
    codeCim10: "A20",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Peste",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Rage",
    codeCim10: "A82",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Rage",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Rickettsioses (Fièvre boutonneuse méditerranéenne)",
    codeCim10: "A77",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Rickettsioses",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Rougeole",
    codeCim10: "B05",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Rougeole",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Rubéole",
    codeCim10: "B06",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Rubéole",
    seuilDefaut: 5,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Schistosomiase (Bilharziose)",
    codeCim10: "B65",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Bilharziose",
    seuilDefaut: 5,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Tétanos néonatal",
    codeCim10: "A33",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Tétanos néo.",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Tétanos non-néonatal",
    codeCim10: "A35",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Tétanos",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Toxi-infection alimentaire collective (TIAC)",
    codeCim10: "A05.9",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "TIAC",
    seuilDefaut: 2,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "tiac",
  },
  {
    nom: "Trachome",
    codeCim10: "A71",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Trachome",
    seuilDefaut: 10,
    categorieGravite: "faible",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Typhus exanthématique",
    codeCim10: "A75",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Typhus",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },

  // ─── Déclaration hebdomadaire (7 jours = 168h) ────────────────────────────

  {
    nom: "Hépatite virale B",
    codeCim10: "B16",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "Hépatite B",
    seuilDefaut: 10,
    categorieGravite: "moderee",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Hépatite virale C",
    codeCim10: "B17",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "Hépatite C",
    seuilDefaut: 10,
    categorieGravite: "moderee",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Infection à Chlamydia",
    codeCim10: "A74",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "Chlamydia",
    seuilDefaut: 10,
    categorieGravite: "faible",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Infection à VIH/SIDA",
    codeCim10: "B24",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "VIH/SIDA",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Syphilis",
    codeCim10: "A53",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "Syphilis",
    seuilDefaut: 5,
    categorieGravite: "moderee",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Urétrite gonococcique",
    codeCim10: "A54",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "hebdomadaire",
    nomCourt: "Gonococcie",
    seuilDefaut: 10,
    categorieGravite: "faible",
    delaiNotificationHeures: 168,
    delaiDeclarationTexte: "Déclaration hebdomadaire (7 jours)",
    hasFicheSpecifique: false,
  },

  // ─── Déclaration mensuelle (30 jours = 720h) ──────────────────────────────

  {
    nom: "Tuberculose pulmonaire",
    codeCim10: "A15",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "mensuelle",
    nomCourt: "TB pulmonaire",
    seuilDefaut: 10,
    categorieGravite: "grave",
    delaiNotificationHeures: 720,
    delaiDeclarationTexte: "Déclaration mensuelle (30 jours)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Tuberculose extra-pulmonaire",
    codeCim10: "A18",
    categorie: "categorie_1_mdo",
    frequenceDeclaration: "mensuelle",
    nomCourt: "TB extra-pulm.",
    seuilDefaut: 10,
    categorieGravite: "grave",
    delaiNotificationHeures: 720,
    delaiDeclarationTexte: "Déclaration mensuelle (30 jours)",
    hasFicheSpecifique: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 2 — Surveillance internationale (14 maladies)
  // ══════════════════════════════════════════════════════════════════════════

  // ─── Déclaration en urgence (< 4h + appel téléphonique) ──────────────────

  {
    nom: "Poliomyélite",
    codeCim10: "A80",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "urgence",
    nomCourt: "Poliomyélite",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 4,
    delaiDeclarationTexte: "Déclaration en urgence (< 4h) + appel téléphonique",
    hasFicheSpecifique: true,
    ficheSpecifiqueSlug: "pfa",
  },

  // ─── Déclaration quotidienne (24h) ────────────────────────────────────────

  {
    nom: "Chikungunya",
    codeCim10: "A92",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Chikungunya",
    seuilDefaut: 5,
    categorieGravite: "moderee",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Choléra",
    codeCim10: "A00",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Choléra",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Dengue",
    codeCim10: "A90",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Dengue",
    seuilDefaut: 5,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Ebola",
    codeCim10: "A984",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Ebola",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Fièvre jaune",
    codeCim10: "A95",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Fièvre jaune",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Fièvre de la Vallée du Rift",
    codeCim10: "A924",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Fièvre du Rift",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Fièvre du West Nile",
    codeCim10: "A923",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "West Nile",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Autres fièvres hémorragiques virales",
    codeCim10: "A988",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Fièvre hémorr.",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Grippe causée par un nouveau sous-type de virus",
    codeCim10: "J10",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Grippe nouveau",
    seuilDefaut: 5,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Syndrome respiratoire aigu sévère (SARS)",
    codeCim10: "U04",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "SARS",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Syndrome respiratoire aigu sévère CoV-2 (SARS-CoV-2)",
    codeCim10: "U07",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "SARS-CoV-2",
    seuilDefaut: 20,
    categorieGravite: "grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Syndrome respiratoire du Moyen-Orient (MERS)",
    codeCim10: "U071",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "MERS",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },
  {
    nom: "Variole",
    codeCim10: "B03",
    categorie: "categorie_2_epidemique",
    frequenceDeclaration: "quotidienne",
    nomCourt: "Variole",
    seuilDefaut: 1,
    categorieGravite: "tres_grave",
    delaiNotificationHeures: 24,
    delaiDeclarationTexte: "Déclaration quotidienne (24h)",
    hasFicheSpecifique: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 3 — BMR (Bactéries Multi-Résistantes) — granularité clinique
  // Sous-ensemble de Cat1 BMR, détaillé par germe pour le suivi en réanimation
  // ══════════════════════════════════════════════════════════════════════════

  { nom: "SARM/MRSA", codeCim10: "U82.0", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "SARM", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "ERV/VRE (Enterococcus faecalis/faecium)", codeCim10: "U82.1", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "ERV", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Enterobacter cloacae multirésistant", codeCim10: "U82.2", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "E. cloacae MR", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "EPC/CRE (Entérobactéries carbapénémases)", codeCim10: "U82.2a", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "EPC/CRE", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "BLSE/ESBL (β-lactamases spectre étendu)", codeCim10: "U82.2b", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "BLSE", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "E. coli multirésistant", codeCim10: "U82.2c", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "E. coli MR", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Klebsiella pneumoniae multirésistante", codeCim10: "U82.2d", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "Klebsiella MR", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Résistance céphalosporines 3e génération", codeCim10: "U82.2e", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "C3G-R", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Pseudomonas aeruginosa multirésistant", codeCim10: "U82.3", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "Pseudomonas MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Acinetobacter baumannii multirésistant", codeCim10: "U82.4", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "Acinetobacter MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "VRSA", codeCim10: "U82.5", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "VRSA", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Autres bactéries résistantes", codeCim10: "U82.8", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "BMR autres", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Stenotrophomonas maltophilia", codeCim10: "U82.8a", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "Stenotrophomonas", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Résistance organisme non spécifié", codeCim10: "U82.9", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "BMR NOS", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "MDR-TB (Mycobacterium tuberculosis MR)", codeCim10: "U83.0", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "MDR-TB", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Tuberculose multirésistante", codeCim10: "U83.0a", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "TB-MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "XDR-TB (Mycobacterium tuberculosis XR)", codeCim10: "U83.1", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "XDR-TB", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Tuberculose ultrarésistante", codeCim10: "U83.1a", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "TB-UR", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 4, delaiDeclarationTexte: "Déclaration en urgence (< 4h)", hasFicheSpecifique: false },
  { nom: "Résistance autres antituberculeux", codeCim10: "U83.8", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "TB-R autres", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Résistance antituberculeux non spécifiée", codeCim10: "U83.9", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "TB-R NOS", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Résistance antiviraux", codeCim10: "U84.0", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "Antiviral-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Résistance antifongiques", codeCim10: "U84.1", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "Antifongique-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Résistance antiparasitaires", codeCim10: "U84.2", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "Antiparasite-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Proteus mirabilis multirésistant", codeCim10: "B96.4", categorie: "categorie_3_bmr", frequenceDeclaration: "urgence", nomCourt: "Proteus MR", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
  { nom: "Morganella morganii multirésistante", codeCim10: "B96.9", categorie: "categorie_3_bmr", frequenceDeclaration: "quotidienne", nomCourt: "Morganella MR", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 24, delaiDeclarationTexte: "Déclaration quotidienne (24h)", hasFicheSpecifique: false },
]
