export const MALADIES_SEED = [
  // ═══ CATÉGORIE 1 — MDO (44 maladies) ═══
  { nom: "Botulisme", codeCim10: "A05.1", categorie: "categorie_1_mdo", nomCourt: "Botulisme", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Brucellose", codeCim10: "A23", categorie: "categorie_1_mdo", nomCourt: "Brucellose", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Charbon", codeCim10: "A22", categorie: "categorie_1_mdo", nomCourt: "Charbon", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Coqueluche", codeCim10: "A37", categorie: "categorie_1_mdo", nomCourt: "Coqueluche", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Diphtérie", codeCim10: "A36", categorie: "categorie_1_mdo", nomCourt: "Diphtérie", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "diphterie" },
  { nom: "Dysenterie amibienne et bacillaire", codeCim10: "A06", categorie: "categorie_1_mdo", nomCourt: "Dysenterie", seuilDefaut: 10, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Echinococcose (Kyste hydatique)", codeCim10: "B67", categorie: "categorie_1_mdo", nomCourt: "Kyste hydatique", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Fièvre typhoïde et paratyphoïde", codeCim10: "A01", categorie: "categorie_1_mdo", nomCourt: "Typhoïde", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Hépatite virale A", codeCim10: "B15", categorie: "categorie_1_mdo", nomCourt: "Hépatite A", seuilDefaut: 10, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Hépatite virale B", codeCim10: "B16", categorie: "categorie_1_mdo", nomCourt: "Hépatite B", seuilDefaut: 10, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Hépatite virale C", codeCim10: "B17", categorie: "categorie_1_mdo", nomCourt: "Hépatite C", seuilDefaut: 10, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Infection à Chlamydia", codeCim10: "A74", categorie: "categorie_1_mdo", nomCourt: "Chlamydia", seuilDefaut: 10, categorieGravite: "faible", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Infection à VIH/SIDA", codeCim10: "B24", categorie: "categorie_1_mdo", nomCourt: "VIH/SIDA", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Infections BMR", codeCim10: "U82", categorie: "categorie_1_mdo", nomCourt: "BMR", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Infections du site opératoire (ISO)", codeCim10: "Y62", categorie: "categorie_1_mdo", nomCourt: "ISO", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Légionellose", codeCim10: "A48", categorie: "categorie_1_mdo", nomCourt: "Légionellose", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Leishmaniose cutanée", codeCim10: "B551", categorie: "categorie_1_mdo", nomCourt: "Leish. cutanée", seuilDefaut: 10, categorieGravite: "moderee", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Leishmaniose viscérale", codeCim10: "B550", categorie: "categorie_1_mdo", nomCourt: "Leish. viscérale", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Lèpre", codeCim10: "A30", categorie: "categorie_1_mdo", nomCourt: "Lèpre", seuilDefaut: 1, categorieGravite: "moderee", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Leptospirose", codeCim10: "A27", categorie: "categorie_1_mdo", nomCourt: "Leptospirose", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Listériose", codeCim10: "A32", categorie: "categorie_1_mdo", nomCourt: "Listériose", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Méningite à haemophilus influenzae b", codeCim10: "G000", categorie: "categorie_1_mdo", nomCourt: "Méningite Hib", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "meningite" },
  { nom: "Méningite à pneumocoque", codeCim10: "G01", categorie: "categorie_1_mdo", nomCourt: "Méningite pneumo", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "meningite" },
  { nom: "Méningites à méningocoque", codeCim10: "G01A39", categorie: "categorie_1_mdo", nomCourt: "Méningite méning.", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "meningite" },
  { nom: "Méningites virales", codeCim10: "G03", categorie: "categorie_1_mdo", nomCourt: "Méningite virale", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "meningite" },
  { nom: "Méningo-encéphalites virales", codeCim10: "G05", categorie: "categorie_1_mdo", nomCourt: "Méningo-encéph.", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Paludisme", codeCim10: "B54", categorie: "categorie_1_mdo", nomCourt: "Paludisme", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Paralysie flasque aiguë (PFA)", codeCim10: "G82", categorie: "categorie_1_mdo", nomCourt: "PFA", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "pfa" },
  { nom: "Peste", codeCim10: "A20", categorie: "categorie_1_mdo", nomCourt: "Peste", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Pneumopathie acquise sous ventilation", codeCim10: "J95", categorie: "categorie_1_mdo", nomCourt: "PASV", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Rage", codeCim10: "A82", categorie: "categorie_1_mdo", nomCourt: "Rage", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Rickettsioses", codeCim10: "A77", categorie: "categorie_1_mdo", nomCourt: "Rickettsioses", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Rougeole", codeCim10: "B05", categorie: "categorie_1_mdo", nomCourt: "Rougeole", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Rubéole", codeCim10: "B06", categorie: "categorie_1_mdo", nomCourt: "Rubéole", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Schistosomiase (Bilharziose)", codeCim10: "B65", categorie: "categorie_1_mdo", nomCourt: "Bilharziose", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Syphilis", codeCim10: "A53", categorie: "categorie_1_mdo", nomCourt: "Syphilis", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Tétanos néonatal", codeCim10: "A33", categorie: "categorie_1_mdo", nomCourt: "Tétanos néo.", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Tétanos non-néonatal", codeCim10: "A35", categorie: "categorie_1_mdo", nomCourt: "Tétanos", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "TIAC", codeCim10: "A05.9", categorie: "categorie_1_mdo", nomCourt: "TIAC", seuilDefaut: 2, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "tiac" },
  { nom: "Trachome", codeCim10: "A71", categorie: "categorie_1_mdo", nomCourt: "Trachome", seuilDefaut: 10, categorieGravite: "faible", delaiNotificationHeures: 72, hasFicheSpecifique: false },
  { nom: "Tuberculose extra-pulmonaire", codeCim10: "A18", categorie: "categorie_1_mdo", nomCourt: "TB extra-pulm.", seuilDefaut: 10, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Tuberculose pulmonaire", codeCim10: "A15", categorie: "categorie_1_mdo", nomCourt: "TB pulmonaire", seuilDefaut: 10, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Typhus exanthématique", codeCim10: "A75", categorie: "categorie_1_mdo", nomCourt: "Typhus", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Urétrite gonococcique", codeCim10: "A54", categorie: "categorie_1_mdo", nomCourt: "Gonococcie", seuilDefaut: 10, categorieGravite: "faible", delaiNotificationHeures: 72, hasFicheSpecifique: false },

  // ═══ CATÉGORIE 2 — Potentiel épidémique (14 maladies) ═══
  { nom: "Choléra", codeCim10: "A00", categorie: "categorie_2_epidemique", nomCourt: "Choléra", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Grippe causée par un nouveau sous-type de virus", codeCim10: "J10", categorie: "categorie_2_epidemique", nomCourt: "Grippe nouveau", seuilDefaut: 5, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Autres fièvres hémorragiques virales", codeCim10: "A988", categorie: "categorie_2_epidemique", nomCourt: "Fièvre hémorr.", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Chikungunya", codeCim10: "A92", categorie: "categorie_2_epidemique", nomCourt: "Chikungunya", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Dengue", codeCim10: "A90", categorie: "categorie_2_epidemique", nomCourt: "Dengue", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Ebola", codeCim10: "A984", categorie: "categorie_2_epidemique", nomCourt: "Ebola", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Fièvre de la Vallée du Rift", codeCim10: "A924", categorie: "categorie_2_epidemique", nomCourt: "Fièvre du Rift", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Fièvre du West Nile", codeCim10: "A923", categorie: "categorie_2_epidemique", nomCourt: "West Nile", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Fièvre jaune", codeCim10: "A95", categorie: "categorie_2_epidemique", nomCourt: "Fièvre jaune", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Poliomyélite", codeCim10: "A80", categorie: "categorie_2_epidemique", nomCourt: "Poliomyélite", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: true, ficheSpecifiqueSlug: "pfa" },
  { nom: "SARS", codeCim10: "U04", categorie: "categorie_2_epidemique", nomCourt: "SARS", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "SARS-CoV-2 (COVID-19)", codeCim10: "U07", categorie: "categorie_2_epidemique", nomCourt: "COVID-19", seuilDefaut: 20, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "MERS", codeCim10: "U071", categorie: "categorie_2_epidemique", nomCourt: "MERS", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Variole", codeCim10: "B03", categorie: "categorie_2_epidemique", nomCourt: "Variole", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },

  // ═══ CATÉGORIE 3 — BMR (25 germes) ═══
  { nom: "SARM/MRSA", codeCim10: "U82.0", categorie: "categorie_3_bmr", nomCourt: "SARM", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "ERV/VRE (Enterococcus faecalis/faecium)", codeCim10: "U82.1", categorie: "categorie_3_bmr", nomCourt: "ERV", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Enterobacter cloacae multirésistant", codeCim10: "U82.2", categorie: "categorie_3_bmr", nomCourt: "E. cloacae MR", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "EPC/CRE (Entérobactéries carbapénémases)", codeCim10: "U82.2a", categorie: "categorie_3_bmr", nomCourt: "EPC/CRE", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "BLSE/ESBL (β-lactamases spectre étendu)", codeCim10: "U82.2b", categorie: "categorie_3_bmr", nomCourt: "BLSE", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "E. coli multirésistant", codeCim10: "U82.2c", categorie: "categorie_3_bmr", nomCourt: "E. coli MR", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Klebsiella pneumoniae multirésistante", codeCim10: "U82.2d", categorie: "categorie_3_bmr", nomCourt: "Klebsiella MR", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Résistance céphalosporines 3e génération", codeCim10: "U82.2e", categorie: "categorie_3_bmr", nomCourt: "C3G-R", seuilDefaut: 5, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Pseudomonas aeruginosa multirésistant", codeCim10: "U82.3", categorie: "categorie_3_bmr", nomCourt: "Pseudomonas MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Acinetobacter baumannii multirésistant", codeCim10: "U82.4", categorie: "categorie_3_bmr", nomCourt: "Acinetobacter MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "VRSA", codeCim10: "U82.5", categorie: "categorie_3_bmr", nomCourt: "VRSA", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Autres bactéries résistantes", codeCim10: "U82.8", categorie: "categorie_3_bmr", nomCourt: "BMR autres", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Stenotrophomonas maltophilia", codeCim10: "U82.8a", categorie: "categorie_3_bmr", nomCourt: "Stenotrophomonas", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Résistance organisme non spécifié", codeCim10: "U82.9", categorie: "categorie_3_bmr", nomCourt: "BMR NOS", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "MDR-TB (Mycobacterium tuberculosis MR)", codeCim10: "U83.0", categorie: "categorie_3_bmr", nomCourt: "MDR-TB", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Tuberculose multirésistante", codeCim10: "U83.0a", categorie: "categorie_3_bmr", nomCourt: "TB-MR", seuilDefaut: 3, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "XDR-TB (Mycobacterium tuberculosis XR)", codeCim10: "U83.1", categorie: "categorie_3_bmr", nomCourt: "XDR-TB", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Tuberculose ultrarésistante", codeCim10: "U83.1a", categorie: "categorie_3_bmr", nomCourt: "TB-UR", seuilDefaut: 1, categorieGravite: "tres_grave", delaiNotificationHeures: 24, hasFicheSpecifique: false },
  { nom: "Résistance autres antituberculeux", codeCim10: "U83.8", categorie: "categorie_3_bmr", nomCourt: "TB-R autres", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Résistance antituberculeux non spécifiée", codeCim10: "U83.9", categorie: "categorie_3_bmr", nomCourt: "TB-R NOS", seuilDefaut: 3, categorieGravite: "grave", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Résistance antiviraux", codeCim10: "U84.0", categorie: "categorie_3_bmr", nomCourt: "Antiviral-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Résistance antifongiques", codeCim10: "U84.1", categorie: "categorie_3_bmr", nomCourt: "Antifongique-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Résistance antiparasitaires", codeCim10: "U84.2", categorie: "categorie_3_bmr", nomCourt: "Antiparasite-R", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Proteus mirabilis multirésistant", codeCim10: "B96.4", categorie: "categorie_3_bmr", nomCourt: "Proteus MR", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
  { nom: "Morganella morganii multirésistante", codeCim10: "B96.9", categorie: "categorie_3_bmr", nomCourt: "Morganella MR", seuilDefaut: 5, categorieGravite: "moderee", delaiNotificationHeures: 48, hasFicheSpecifique: false },
]
