-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_cas_declares" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "code_cas" TEXT NOT NULL,
    "patient_id" TEXT NOT NULL,
    "maladie_id" TEXT NOT NULL,
    "date_debut_symptomes" DATETIME NOT NULL,
    "date_diagnostic" DATETIME NOT NULL,
    "mode_confirmation" TEXT,
    "resultat_labo" TEXT,
    "statut" TEXT NOT NULL DEFAULT 'nouveau',
    "etablissement_id" TEXT,
    "service" TEXT,
    "medecin_id" TEXT,
    "notes_cliniques" TEXT,
    "commune_id" TEXT,
    "latitude" DECIMAL,
    "longitude" DECIMAL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "nin" TEXT,
    "age_ans" INTEGER,
    "age_mois" INTEGER,
    "age_jours" INTEGER,
    "profession" TEXT,
    "email_patient" TEXT,
    "lieu_travail" TEXT,
    "est_etranger" BOOLEAN,
    "nationalite" TEXT,
    "symptomes_texte" TEXT,
    "observation" TEXT,
    "atcd" TEXT,
    "lieux_frequentes" TEXT,
    "cas_similaire" BOOLEAN,
    "est_hospitalise" BOOLEAN,
    "date_hospitalisation" DATETIME,
    "est_evacue" BOOLEAN,
    "date_evacuation" DATETIME,
    "structure_evacuation" TEXT,
    "type_prelevement" TEXT,
    "date_prelevement" DATETIME,
    "destinataire_prelevements" TEXT,
    "evolution" TEXT,
    "date_sortie" DATETIME,
    "date_deces" DATETIME,
    "service_declarant" TEXT,
    "mois_declaration" INTEGER,
    "annee_declaration" INTEGER,
    "donnees_specifiques" JSONB,
    "fiche_specifique_type" TEXT,
    "nationalite_code" TEXT,
    "cas_similaire_id" TEXT,
    "evaluation_clinique" JSONB,
    "structure_hospitalisation_id" TEXT,
    "service_hospitalisation" TEXT,
    CONSTRAINT "cas_declares_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "patients" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_maladie_id_fkey" FOREIGN KEY ("maladie_id") REFERENCES "maladies" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_etablissement_id_fkey" FOREIGN KEY ("etablissement_id") REFERENCES "etablissements" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_medecin_id_fkey" FOREIGN KEY ("medecin_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_commune_id_fkey" FOREIGN KEY ("commune_id") REFERENCES "communes" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_cas_similaire_id_fkey" FOREIGN KEY ("cas_similaire_id") REFERENCES "cas_declares" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "cas_declares_structure_hospitalisation_id_fkey" FOREIGN KEY ("structure_hospitalisation_id") REFERENCES "etablissements" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_cas_declares" ("age_ans", "age_jours", "age_mois", "annee_declaration", "atcd", "cas_similaire", "cas_similaire_id", "code_cas", "commune_id", "created_at", "date_debut_symptomes", "date_deces", "date_diagnostic", "date_evacuation", "date_hospitalisation", "date_prelevement", "date_sortie", "destinataire_prelevements", "donnees_specifiques", "email_patient", "est_etranger", "est_evacue", "est_hospitalise", "etablissement_id", "evaluation_clinique", "evolution", "fiche_specifique_type", "id", "latitude", "lieu_travail", "lieux_frequentes", "longitude", "maladie_id", "medecin_id", "mode_confirmation", "mois_declaration", "nationalite", "nationalite_code", "nin", "notes_cliniques", "observation", "patient_id", "profession", "resultat_labo", "service", "service_declarant", "service_hospitalisation", "statut", "structure_evacuation", "structure_hospitalisation_id", "symptomes_texte", "type_prelevement", "updated_at") SELECT "age_ans", "age_jours", "age_mois", "annee_declaration", "atcd", "cas_similaire", "cas_similaire_id", "code_cas", "commune_id", "created_at", "date_debut_symptomes", "date_deces", "date_diagnostic", "date_evacuation", "date_hospitalisation", "date_prelevement", "date_sortie", "destinataire_prelevements", "donnees_specifiques", "email_patient", "est_etranger", "est_evacue", "est_hospitalise", "etablissement_id", "evaluation_clinique", "evolution", "fiche_specifique_type", "id", "latitude", "lieu_travail", "lieux_frequentes", "longitude", "maladie_id", "medecin_id", "mode_confirmation", "mois_declaration", "nationalite", "nationalite_code", "nin", "notes_cliniques", "observation", "patient_id", "profession", "resultat_labo", "service", "service_declarant", "service_hospitalisation", "statut", "structure_evacuation", "structure_hospitalisation_id", "symptomes_texte", "type_prelevement", "updated_at" FROM "cas_declares";
DROP TABLE "cas_declares";
ALTER TABLE "new_cas_declares" RENAME TO "cas_declares";
CREATE UNIQUE INDEX "cas_declares_code_cas_key" ON "cas_declares"("code_cas");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
