// ISO 3166-1 alpha-2 country codes with French names
// Sorted alphabetically by French name, Algeria first
export const NATIONALITIES = [
  { code: "DZ", label: "Algérie" },
  { code: "AF", label: "Afghanistan" },
  { code: "ZA", label: "Afrique du Sud" },
  { code: "AL", label: "Albanie" },
  { code: "DE", label: "Allemagne" },
  { code: "SA", label: "Arabie Saoudite" },
  { code: "AR", label: "Argentine" },
  { code: "AU", label: "Australie" },
  { code: "AT", label: "Autriche" },
  { code: "BH", label: "Bahreïn" },
  { code: "BD", label: "Bangladesh" },
  { code: "BE", label: "Belgique" },
  { code: "BJ", label: "Bénin" },
  { code: "BR", label: "Brésil" },
  { code: "BF", label: "Burkina Faso" },
  { code: "CM", label: "Cameroun" },
  { code: "CA", label: "Canada" },
  { code: "TD", label: "Tchad" },
  { code: "CN", label: "Chine" },
  { code: "CO", label: "Colombie" },
  { code: "KM", label: "Comores" },
  { code: "CG", label: "Congo" },
  { code: "CD", label: "Congo (RDC)" },
  { code: "CI", label: "Côte d'Ivoire" },
  { code: "HR", label: "Croatie" },
  { code: "CU", label: "Cuba" },
  { code: "DK", label: "Danemark" },
  { code: "DJ", label: "Djibouti" },
  { code: "EG", label: "Égypte" },
  { code: "AE", label: "Émirats Arabes Unis" },
  { code: "ES", label: "Espagne" },
  { code: "US", label: "États-Unis" },
  { code: "ET", label: "Éthiopie" },
  { code: "FI", label: "Finlande" },
  { code: "FR", label: "France" },
  { code: "GA", label: "Gabon" },
  { code: "GH", label: "Ghana" },
  { code: "GR", label: "Grèce" },
  { code: "GN", label: "Guinée" },
  { code: "HU", label: "Hongrie" },
  { code: "IN", label: "Inde" },
  { code: "ID", label: "Indonésie" },
  { code: "IQ", label: "Irak" },
  { code: "IR", label: "Iran" },
  { code: "IE", label: "Irlande" },
  { code: "IT", label: "Italie" },
  { code: "JP", label: "Japon" },
  { code: "JO", label: "Jordanie" },
  { code: "KE", label: "Kenya" },
  { code: "KW", label: "Koweït" },
  { code: "LB", label: "Liban" },
  { code: "LY", label: "Libye" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malaisie" },
  { code: "ML", label: "Mali" },
  { code: "MA", label: "Maroc" },
  { code: "MR", label: "Mauritanie" },
  { code: "MX", label: "Mexique" },
  { code: "NE", label: "Niger" },
  { code: "NG", label: "Nigéria" },
  { code: "NO", label: "Norvège" },
  { code: "NZ", label: "Nouvelle-Zélande" },
  { code: "OM", label: "Oman" },
  { code: "UG", label: "Ouganda" },
  { code: "PK", label: "Pakistan" },
  { code: "PS", label: "Palestine" },
  { code: "NL", label: "Pays-Bas" },
  { code: "PH", label: "Philippines" },
  { code: "PL", label: "Pologne" },
  { code: "PT", label: "Portugal" },
  { code: "QA", label: "Qatar" },
  { code: "RO", label: "Roumanie" },
  { code: "GB", label: "Royaume-Uni" },
  { code: "RU", label: "Russie" },
  { code: "RW", label: "Rwanda" },
  { code: "SN", label: "Sénégal" },
  { code: "RS", label: "Serbie" },
  { code: "SL", label: "Sierra Leone" },
  { code: "SO", label: "Somalie" },
  { code: "SD", label: "Soudan" },
  { code: "SE", label: "Suède" },
  { code: "CH", label: "Suisse" },
  { code: "SY", label: "Syrie" },
  { code: "TZ", label: "Tanzanie" },
  { code: "TN", label: "Tunisie" },
  { code: "TR", label: "Turquie" },
  { code: "UA", label: "Ukraine" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yémen" },
] as const

export type NationalityCode = (typeof NATIONALITIES)[number]["code"]
